FROM i386/alpine:3.7
RUN apk update && apk add --update --no-cache alpine-base bash xvfb libstdc++ curl nodejs nodejs-npm git wine && rm -rf /var/cache/apk/*

RUN wget http://winetricks.org/winetricks && chmod +x winetricks && mv winetricks /usr/bin/winetricks

ENV WINEARCH win32
ENV DISPLAY :0
ENV SDK_TOOLS "4333796"
ENV BUILD_TOOLS "28.0.2"
ENV TARGET_SDK "28"
ENV ANDROID_HOME "/opt/sdk"
ENV GLIBC_VERSION "2.27-r0"

RUN apk add --update --no-cache gradle

# Install required dependencies
RUN apk add --no-cache --virtual=.build-dependencies wget unzip ca-certificates bash && \
  wget https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub -O /etc/apk/keys/sgerrand.rsa.pub && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk -O /tmp/glibc.apk && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk -O /tmp/glibc-bin.apk && \
  apk add --no-cache /tmp/glibc.apk /tmp/glibc-bin.apk && \
  rm -rf /tmp/* && \
  rm -rf /var/cache/apk/*

# Download and extract Android Tools
RUN wget http://dl.google.com/android/repository/sdk-tools-linux-${SDK_TOOLS}.zip -O /tmp/tools.zip && \
  mkdir -p ${ANDROID_HOME} && \
  unzip /tmp/tools.zip -d ${ANDROID_HOME} && \
  rm -v /tmp/tools.zip

# Install SDK Packages
RUN mkdir -p /root/.android/ && touch /root/.android/repositories.cfg && \
  yes | ${ANDROID_HOME}/tools/bin/sdkmanager "--licenses" && \
  ${ANDROID_HOME}/tools/bin/sdkmanager "--update" && \
  ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;${BUILD_TOOLS}" "platform-tools" "platforms;android-${TARGET_SDK}" "extras;android;m2repository" "extras;google;google_play_services" "extras;google;m2repository" "emulator"
# === Install Cordova ===
RUN npm install --global cordova \
  && cordova telemetry off \
  && npm cache clean --force \
  # === Prepare & cache Cordova Android platform & build tools
  && cordova create /tmp/dummy dummy.app DummyApp \
  && cd /tmp/dummy \
  && cordova platform add android \
  && cordova build android \
  && rm -rf /tmp/dummy

RUN npm install -g quasar-cli@0.6.5 


RUN rm -r -f ~/.wine
RUN WINEARCH=win32 WINEPREFIX=~/.wine
#RUN npm install -g cypress


RUN mkdir /tmp/app

WORKDIR /tmp/app

VOLUME ["/tmp/app"]

CMD tail -f /dev/null

